force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Name</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Options__c/Survey_Question_Options__c.object-meta.xml
<CustomObject>
    <label>Survey Question Option</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Survey Question Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question_Options__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Question Options</relationshipLabel>
    <relationshipName>Survey_Question_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Translated_Response__c.field-meta.xml
<CustomField>
    <fullName>Translated_Response__c</fullName>
    <label>Translated Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SurveyFormController.cls
public without sharing class SurveyFormController {

    @AuraEnabled(cacheable=true)
    public static Event__c getEventDetails(String eventId) {
        System.debug('Event Id: ' + eventId);
        return [SELECT Id, Name, Logo_Url__c FROM Event__c WHERE Id = :eventId LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Object> getSurveyQuestions(String eventId) {
        List<Object> surveyQuestions = new List<Object>();
        try {
            System.debug('Fetching surveys for eventId: ' + eventId);
            List<Survey__c> surveys = [SELECT Id, Question__c, Question_Type__c 
                                       FROM Survey__c 
                                       WHERE Event_Name__c = :eventId];
            System.debug('Fetched surveys: ' + surveys);

            for (Survey__c survey : surveys) {
                Map<String, Object> questionMap = new Map<String, Object>();
                questionMap.put('id', survey.Id);
                questionMap.put('question', survey.Question__c);
                questionMap.put('questionType', survey.Question_Type__c);
                System.debug('Processing survey: ' + survey);

                if (survey.Question_Type__c == 'radio' || survey.Question_Type__c == 'multi-select') {
                    List<Object> optionsList = new List<Object>();
                    List<Survey_Question_Options__c> options = [SELECT Id, Option__c 
                                                                 FROM Survey_Question_Options__c 
                                                                 WHERE Survey_Question__c = :survey.Id];
                    System.debug('Fetched options for survey ' + survey.Id + ': ' + options);
                    for (Survey_Question_Options__c option : options) {
                        Map<String, Object> optionMap = new Map<String, Object>();
                        optionMap.put('id', option.Id);
                        optionMap.put('option', option.Option__c);
                        optionsList.add(optionMap);
                    }
                    questionMap.put('options', optionsList);
                }
                surveyQuestions.add(questionMap);
            }
            System.debug('Survey questions mapped: ' + surveyQuestions);
        } catch (Exception e) {
            System.debug('Error in getSurveyQuestions: ' + e.getMessage());
        }
        return surveyQuestions;
    }

    @AuraEnabled
    public static List<Survey_Response__c> saveSurveyResponses(Id eventId, Id attendeeId, List<Map<String, String>> surveyResponses) {
        List<Survey_Response__c> responsesToInsert = new List<Survey_Response__c>();
        Set<Id> questionIds = new Set<Id>();
        Map<Id, String> questionNames = new Map<Id, String>();
        
        for (Map<String, String> response : surveyResponses) {
            questionIds.add(response.get('questionId'));
        }
        
        if (!questionIds.isEmpty()) {
            List<Survey__c> questions = [SELECT Id, Name FROM Survey__c WHERE Id IN :questionIds];
            for (Survey__c question : questions) {
                questionNames.put(question.Id, question.Name);
            }
        }
        
        String attendeeName = '';
        if (attendeeId != null) {
            List<Attendee__c> attendees = [SELECT Id, Name FROM Attendee__c WHERE Id = :attendeeId LIMIT 1];
            if (!attendees.isEmpty()) {
                attendeeName = attendees[0].Name;
            }
        }
        
        for (Map<String, String> response : surveyResponses) {
            Survey_Response__c surveyResponse = new Survey_Response__c();
            surveyResponse.Event__c = eventId;
            surveyResponse.Attendee__c = attendeeId;
            surveyResponse.Survey_Question__c = response.get('questionId');
            surveyResponse.Response__c = response.get('response');
            
            String questionId = response.get('questionId');
            String questionName = questionNames.get(questionId);
           
                surveyResponse.Name = questionName + ' - ' + attendeeName;
           
            
            responsesToInsert.add(surveyResponse);
        }
        
        try {
            insert responsesToInsert;
            return responsesToInsert;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    

//     @future(callout=true)
//     public static void translateResponse(String responseJson) {
//         List<Survey_Response__c> responses = (List<Survey_Response__c>) JSON.deserialize(responseJson, List<Survey_Response__c>.class);
//         System.debug('Deserialized responses: ' + responses);
    

//         List<Survey_Response__c> responsesToUpdate = new List<Survey_Response__c>();
    
       
//         for (Survey_Response__c response : responses) {
//             String prompt = 'If the content of the response is not in English, then translate the text into English: ' + response.Response__c;
            
      
//             String translatedResponse = SurveyController.promptGenerations(prompt);
    
          
//             response.Translated_Response__c = translatedResponse;
    
//             responsesToUpdate.add(response);
//         }
//         try {
//             update responsesToUpdate;

//     }
//     catch (Exception e){
//         System.debug('Error in translating response: ' +e.getMessage());
//     }
    

// }
}