force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Name</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question_Options__c/Survey_Question_Options__c.object-meta.xml
<CustomObject>
    <label>Survey Question Option</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Survey Question Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question_Options__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Question Options</relationshipLabel>
    <relationshipName>Survey_Question_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveyController.cls
public class SurveyController {
        @AuraEnabled
        public static void saveSurvey(Id eventId, String surveyQuestionsJSON) {
            try {
                
                List<SurveyQuestion> surveyQuestions = (List<SurveyQuestion>) JSON.deserialize(surveyQuestionsJSON, List<SurveyQuestion>.class);
    
                List<Survey__c> questionsToInsert = new List<Survey__c>();
                List<Survey_Question_Options__c> optionsToInsert = new List<Survey_Question_Options__c>();
    
                for (SurveyQuestion questionData : surveyQuestions) {
                    Survey__c question = new Survey__c();
                    // question.Event_Name__c = eventName;
                    question.Event_Name__c = eventId;
                    question.Question__c = questionData.question;
                    question.Question_Type__c = questionData.dataType;
                    questionsToInsert.add(question);
                }
    
                insert questionsToInsert;
    
                for (Integer i = 0; i < questionsToInsert.size(); i++) {
                    SurveyQuestion questionData = surveyQuestions[i];
                    Survey__c insertedQuestion = questionsToInsert[i];
    
                    if (questionData.options != null) {
                        for (SurveyOption optionData : questionData.options) {
                            Survey_Question_Options__c option = new Survey_Question_Options__c();
                            option.Survey_Question__c = insertedQuestion.Id;
                            option.Option__c = optionData.label;
                            optionsToInsert.add(option);
                        }
                    }
                }
    
                insert optionsToInsert;
            } catch (Exception e) {
                throw new AuraHandledException('Error saving survey: ' + e.getMessage());
            }
        }
    
        public class SurveyQuestion {
            public String question { get; set; }
            public String dataType { get; set; }
            public List<SurveyOption> options { get; set; }
        }
    
        public class SurveyOption {
            public String label { get; set; }
            public String value { get; set; }
        }
}